/********************************************************************
* JTupleDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JTupleDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJTupleDict();
extern void G__cpp_setup_inheritanceJTupleDict();
extern void G__cpp_setup_typetableJTupleDict();
extern void G__cpp_setup_memvarJTupleDict();
extern void G__cpp_setup_globalJTupleDict();
extern void G__cpp_setup_memfuncJTupleDict();
extern void G__cpp_setup_funcJTupleDict();
extern void G__set_cpp_environmentJTupleDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../include/JTuple.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JTupleDictLN_TClass;
extern G__linked_taginfo G__JTupleDictLN_TBuffer;
extern G__linked_taginfo G__JTupleDictLN_TMemberInspector;
extern G__linked_taginfo G__JTupleDictLN_TObject;
extern G__linked_taginfo G__JTupleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JTupleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JTupleDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JTupleDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JTupleDictLN_JTuple;

/* STUB derived class for protected member access */
