#! /bin/sh

if [ -z "$ILCSOFT" ]; then
    echo " You should source an init_ilcsoft.sh script"
    exit
fi

mkbuild()
{
    if [ -d build ]; then
	rm -r build
    fi
    mkdir build
}

build()
{
    echo "============================================================"
    echo "=                 Build Makefile for compilation           ="
    echo "============================================================"    
    echo "---------->  Create a new Makefile  .. "
    cd ${PWD}/build
    cmake -C ${ILCSOFT}/ILCSoft.cmake ..
    ls -lthr
    cd ${PWD}/..
}

compile()
{
    echo "============================================================"
    echo "=                      Compilation                         ="
    echo "============================================================"
    echo "---------->  Compilation  .. "
    cd ${PWD}/build
    make install
    cd ${PWD}/..
}

#The script

#WHAT=$1
#
#if [ "$WHAT" == "Full" ]; then
#    generateRootDict
#    CreateBuildDir
#    cd build
#    CreateMakefile
#    cd ..
#fi
#
#cd build
#Compile
#echo " Compilation done"


